print("A",end="@")
print("b",end="\n")
print("a")
print("c",end = "#")
print("A",end = "#")
print("B",end = "#")
print("C",end = "#")
print("D",end = "#")
print("E",end = "\n")
print("A",10,2.5,sep="\n")
print("D",10,2.5,end="\n")